# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47a10354b13bf2334dc5e985054f224205d02bcf31f4817fa88c127160e37596b2deec07ae8f84de98b55e08ae9536ba5870bcb049113b650141d6bf8d4fb7f6

test:
  secret_key_base: d8c03ad687d4f62f9f3591e2a475276c6931f74a1f32069ed0a342e6b46f16ece62afc32b95383d8441527b609c57c29974d3557ad78893128e4a809c52e24f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
